---
title: "Magic the Gathering Project"
author: "Kevin Howlett"
date: "11/5/2020"
output: html_document
---

```{r}
library(ggplot2)
library(plotly)
library(dplyr)
library(lubridate)
library(ggthemes)
library(stringr)
library(extrafont)
library(ggpubr)

# Set "marketDf" to csv "MTG Market Info.csv" Conor scraped
# "mtg" is the same df as "mtg" in cleanCards.Rmd

marketDf$Market.Price <- as.numeric(gsub("\\$", "", marketDf$Market.Price))
marketDf$Listed.Median <- as.numeric(gsub("\\$", "", marketDf$Listed.Median))

mergedDf <- dplyr::left_join(marketDf, mtg, by=c("Card.Name" = "name"))
mergedDf$releaseDate <- as.Date(mergedDf$releaseDate)


# Group by both rarity and card artist
# Averaged market prices of cards in each of these groups
artistDf <- aggregate( Market.Price ~ rarity+artist, mergedDf, mean )

# Histogram of artists' average card selling price
fig <- artistDf %>%
  plot_ly(
  type='histogram',
  nbinsx = 30,
  x=~Market.Price,
  bingroup=1, color = ~rarity) %>%
  layout(title = 'Average Market Price by Artist',
         xaxis = list(title = 'Avg Market Price [USD]',range = c(-10, 135)))

fig

# Boxplot of artists' selling prices
artistDf %>%
  plot_ly() %>% 
  add_trace(x = ~as.numeric(rarity),y = ~Market.Price, color = ~rarity, type = "box", 
            hoverinfo = 'name+y') %>%
  add_markers(x = ~jitter(as.numeric(rarity)), y = ~Market.Price, color = ~rarity,
              marker = list(size = 6),
              hoverinfo = "text",
              text = ~paste0("Artist: ",artist,
                             "<br>Rarity: ",rarity,
                             "<br>Avg Price: ",round(Market.Price,2)),
              showlegend = FALSE) %>% 
  layout(legend = list(orientation = "h",
                       x =0.6, xanchor = "center",
                       y = 1, yanchor = "bottom"
                       ),
         xaxis = list(title = "Rarity",
                      showticklabels = FALSE),
         yaxis = list(title = "Avg Market Price [USD]",
                      showticklabels = FALSE),
         title = list(text = 'Price by Card Artist',
                      x = 0.08))


```

```{r}
# Group by both rarity and card "type"
# Averaged market prices of cards in each of these groups
typeDf <- aggregate( Market.Price ~ rarity+type, mergedDf, mean )

# Histogram of average market price by card type (i.e. land, creature, etc.)
fig <- typeDf %>%
  plot_ly(
  type='histogram',
  nbinsx = 40,
  x=~Market.Price,
  bingroup=1, color = ~rarity) %>%
  layout(title = 'Average Market Price by Card Type',
         xaxis = list(title = 'Avg Market Price [USD]',range = c(-3, 65)))

fig

# Boxplot average market price by card type (i.e. land, creature, etc.)
typeDf %>%
  plot_ly() %>% 
  add_trace(x = ~as.numeric(rarity),y = ~Market.Price, color = ~rarity, type = "box", 
            hoverinfo = 'name+y') %>%
  add_markers(x = ~jitter(as.numeric(rarity)), y = ~Market.Price, color = ~rarity,
              marker = list(size = 6),
              hoverinfo = "text",
              text = ~paste0("Type: ",type,
                             "<br>Rarity: ",rarity,
                             "<br>Avg Price: ",round(Market.Price,2)),
              showlegend = FALSE) %>% 
  layout(legend = list(orientation = "h",
                       x =0.6, xanchor = "center",
                       y = 1, yanchor = "bottom"
                       ),
         xaxis = list(title = "Rarity",
                      showticklabels = FALSE),
         yaxis = list(title = "Avg Market Price [USD]",
                      showticklabels = FALSE),
         title = list(text = 'Price by Card Type',
                      x = 0.08))
```

```{r}

setDf <- aggregate( Market.Price ~ rarity+Set.Name, mergedDf, mean )

# Histogram of average market price by card set (i.e. Alpha Edition, Arabian Nights, etc.)
fig <- setDf %>%
  plot_ly(
  type='histogram',
  nbinsx = 30,
  x=~Market.Price,
  bingroup=1, color = ~rarity) %>%
  layout(title = 'Average Market Price by Card Set',
         xaxis = list(title = 'Avg Market Price [USD]',range = c(-10, 140)))

fig

setDf %>%
  plot_ly() %>% 
  add_trace(x = ~as.numeric(rarity),y = ~Market.Price, color = ~rarity, type = "box", 
            hoverinfo = 'name+y') %>%
  add_markers(x = ~jitter(as.numeric(rarity)), y = ~Market.Price, color = ~rarity,
              marker = list(size = 6),
              hoverinfo = "text",
              text = ~paste0("Set: ",Set.Name,
                             "<br>Rarity: ",rarity,
                             "<br>Avg Price: ",round(Market.Price,2)),
              showlegend = FALSE) %>% 
  layout(legend = list(orientation = "h",
                       x =0.6, xanchor = "center",
                       y = 1, yanchor = "bottom"
                       ),
         xaxis = list(title = "Rarity",
                      showticklabels = FALSE),
         yaxis = list(title = "Avg Market Price [USD]",
                      showticklabels = FALSE),
         title = list(text = 'Price by Card Set',
                      x = 0.08))




```




```{r}
# Create new attribute of summed power and toughness
mergedDf$power.toughness <- mergedDf$power + mergedDf$toughness


# The next four plots (arranged with ggarrange) investigate the relationship
# of market price vs toughness, mana cost, and power
power.scatter <- mergedDf %>% 
  ggplot(.,aes(y = Market.Price, x = power, color = rarity)) +
  geom_point()+ylab('Market Price')+xlab('Power')+ylim(0,610)+
  ggtitle('Price v. Power')+theme(plot.title = element_text(hjust = 0.5))+theme(legend.position="none")

toughness.scatter <- mergedDf %>% 
  ggplot(.,aes(y = Market.Price, x = toughness, color = rarity)) +
  geom_point()+ylab('Market Price')+xlab('Toughness')+ylim(0,610)+
  ggtitle('Price v. Toughness')+theme(plot.title = element_text(hjust = 0.5)) + theme(legend.position="none")

mana.scatter <- subset(mergedDf, mergedDf$convertedManaCost != max(mergedDf$convertedManaCost, na.rm=T)) %>% 
  ggplot(.,aes(y = Market.Price, x = convertedManaCost, color = rarity)) +
  geom_point()+ylab('Market Price')+xlab('Mana Cost')+ylim(0,610)+
  ggtitle('Price v. Mana Cost')+theme(plot.title = element_text(hjust = 0.5)) + theme(legend.position="none")
  
net.scatter <- mergedDf %>% 
  ggplot(.,aes(y = Market.Price, x = power.toughness, color = rarity)) +
  geom_point()+ylab('Market Price')+xlab('Power + Toughness')+ylim(0,610)+
  ggtitle('Price v. Power + Toughness')+theme(plot.title = element_text(hjust = 0.5))

ggarrange(power.scatter, toughness.scatter, mana.scatter, net.scatter)

```



```{r}
# 3D scatter plot of power, toughness, mana cost (w/ color mapped to rarity)
# Shows linear relationship between power, toughness, and mana
fig <- plot_ly(mergedDf, x = ~power, y = ~toughness, z = ~convertedManaCost, color = ~rarity)
fig <- fig %>% add_markers(hoverinfo = "text",
              text = ~paste0("Power: ",power,
                             "<br>Toughness: ",toughness,
                             "<br>Mana Cost: ",convertedManaCost
                             ))
fig <- fig %>% layout(scene = list(xaxis = list(title = 'Power'),
                     yaxis = list(title = 'Toughness'),
                     zaxis = list(title = 'Mana Cost')),
                     title = list(text = 'Mana Cost v Power/Toughness'))

fig
```













